apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: main
        image: "nginx:1.14.2:"
